services:
  webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./WebApi:/app
      - /app/bin
      - /app/obj
      - /app/WebApi.csproj.nuget.g.props
    working_dir: /app
    container_name: shift_planner_web_api
    depends_on:
      - shift_planner_db
  shift_planner_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgres/data
    container_name: shift_planner_db
volumes:
  db_data: